export const homeObjOne = {
  id: 'homeowner',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'For Homeowners',
  headLine: 'Get more value for your homes',
  desc: 'With our  cutting-edge technological features, Parkinspot makes it easy to connect with customers who are willing to pay for parking their cars. Making money from the comfort of your home has been made easy with Parkinspot',
  buttonLabel: 'Learn more about Homeowners',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'house',
  dark: true,
  primary: true,
  darkText: true,
}

export const homeObjTwo = {
  id: 'customers',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'For Customers',
  headLine: 'Get more value for your homes',
  desc: 'With our  cutting-edge technological features, Parkinspot makes it easy to connect with customers who are willing to pay for parking their cars. Making money from the comfort of your home has been made easy with Parkinspot',
  buttonLabel: 'Learn more about Customers',
  imgStart: true,
  img: require('../../images/car.svg').default,
  alt: 'car',
  dark: true,
  primary: true,
  darkText: true,
}

export const homeObjThree = {
  id: 'payment',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Easy payment plan',
  headLine: 'Get more value for your homes',
  desc: 'With our  cutting-edge technological features, Parkinspot makes it easy to connect with customers who are willing to pay for parking their cars. Making money from the comfort of your home has been made easy with Parkinspot',
  buttonLabel: 'Sign up for free now!',
  imgStart: false,
  img: require('../../images/payment.svg').default,
  alt: 'house',
  dark: true,
  primary: true,
  darkText: true,
}
